Decaffeinate ci spec
pulsar-edit/ppm pull request #21
Opened 2022-11-08 09:45 UTC by GuilleW

Since I work on many files, I edit `package.json` to add useful shortcut to avoid misspelt filename.

```json
    "test-decaff": "npx coffee --compile --output spec spec/${npm_config_name}.coffee",
    "test-coffee": "jasmine-focused --captureExceptions --coffee spec/${npm_config_name}.coffee",
    "test-js": "jasmine-focused --captureExceptions spec/${npm_config_name}.js"
```

## Steps to reproduce decaffeination ([guidelines](https://github.com/pulsar-edit/.github/blob/main/project-birth/CONTRIBUTING-DURING-START.md#decaffeination)):

- [x] Check package.json for coffee-script version
  - version: 1.12.7
- [x] Decaffeination with official Coffee program
  - `npx coffee --compile --output spec spec/ci-spec.coffee`
  - (or my shortcut:  `./bin/npm run test-decaff --name=ci-spec`)
- [x] Quality of Decaffeination
  - [x] Replace `var` with `const` and `let` if it's possible.
  - [x] Replace Nested [Ternary Operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) with if statements.
  - [x] Remove `return` when it's not needed.
  - [x] Remove Result Arrays when they are not needed.
  - [x] Replace for loops with [for-of loops](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of).
  - [x] Use [Arrow Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) to write functions in a single line when it's possible.
  - [x] Remove unneeded ref variables.
  - [x] Remove [do blocks](https://devdocs.io/coffeescript~1/index#loops) and use let or const instead.
  - [x] Tests and assertions should be the same and success like in `coffee` file
  
## Test from coffee and JS should output same successful result :

From coffee
```sh
$ jasmine-focused --captureExceptions --coffee spec/ci-spec.coffee
// or my shortcut $ `./bin/npm run test-coffee --name=ci-spec`
> 4 tests, 8 assertions, 0 failures, 0 skipped
```
to js
```sh
$ jasmine-focused --captureExceptions spec/ci-spec.js
// or my shortcut $ `./bin/npm run test-js --name=ci-spec`
> 4 tests, 8 assertions, 0 failures, 0 skipped
```

2022-12-28 03:41 UTC, confused-Techie requested changes
Overall this PR looks great, just some simple changes requested, otherwise lets get it merged!

2022-12-28 03:41 UTC, confused-Techie commented on spec/ci-spec.js
> +    var done = false
```suggestion
    let done = false
```

2022-12-28 03:41 UTC, confused-Techie commented on spec/ci-spec.js
> +    var live = false
```suggestion
    let live = false
```

2022-12-28 03:41 UTC, confused-Techie commented on spec/ci-spec.js
> +    var live = false
```suggestion
    let live = false
```

2022-12-28 03:41 UTC, confused-Techie commented on spec/ci-spec.js
> +  var server
```suggestion
  let server
```

2023-03-28 18:53 UTC, 2colours commented
Supposedly superseeded by https://github.com/pulsar-edit/ppm/pull/65

2023-05-19 00:58 UTC, confused-Techie commented
Superseded by #65 

Thanks again @GuilleW for your fantastic work here, sorry it has taken some time to get it merged in some form. Appreciate your efforts!

2023-05-19 00:58 UTC, closed without merging